baseURL: https://mujin-lin.netlify.app/
languageCode: en-us
title: Welcome to Mujin Lin's website # change to customize it
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Welcome to my website, My name is Mujin Lin. 
      These are my stories and experiences, have a nice day!
    title: Mujin Lin, MFA2022, LBS # Add your real name and short description
  blog: {}
  contact:
    address:
      - city: London, W9 1SP
        country: United Kingdom
        street: Maida Vale
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: mlin.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (44) 7422581615
        title: Phone
  custom_css: []
  custom_js: []
  description: Feel free to contact me!
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    #copyright: Not available
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design from: '
        url: https://www.html5up.net
    social:
      #- icon: fa-twitter
        #label: Twitter
        #url: https://www.twitter.com
      #- icon: fa-facebook
        #label: Facebook
        #url: https://www.facebook.com
      #- icon: fa-instagram
        #label: Instagram
        #url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/lynloowoo/
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/mujin-lin-b71b301b7/
  image: ''
  name: Mujin Lin
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs
      - name: Elements
        url: elements.html # need to change here, find this rmd Note_
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: Infer
        title: Best Model to Predict Price 
        url: blogs/BMPP
      - image: London_night.jpg 
        subtitle: Every experience surprises me
        title: Life in London
        url: blogs/london_night # slug
      - image: FF.jpg 
        subtitle: It is always a pleasure to spent some time with them
        title: Life with my family and friends
        url: blogs/ff #slug
      - image: She.png
        subtitle: Don't go gentle into that night
        title: She
        url: blogs/she
      - image: Best_memory.jpg
        subtitle: All models are wrong, but some are useful - George Box
        title: Best moment of my life
        url: blogs/best_memory
      - image: Tigers.jpeg
        subtitle: Guangdong Southeast Tigers
        title: My favourite team
        url: blogs/tigers
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Thank you for reading this website. I really apprecitate 
    someone would spent time listening to my story. I am always curious 
    about the world and learning R is really the chance for me to 
    explore more and present all of them. Therefore, if you are free to 
    plan your life, I really recommend you to learn R, which is a beautify
    , readable, and great programming language. Thank you again, my listener!"
    title: Have a nice day!
    url: blogs
